### ISSUE TITLE
SD write not work for XC 6.01

### ISSUE THREAD

**Issue by WanderMax** [Richard-Tung/SDLink#1]
SD write not work for XC 6.01
And any new process for this project, like support N?

**Comment by Richard-Tung** [comment]
i'm still not understand how android handle file permissions on Android M, so enhanced mode may not work, compatibility mode should work fine(compatibility mode may leak some file).
if you figure out the way to handle this, please contact me or submit a patch.

i'm still using the phone running on Android M, so current no N support. i'll try to make this module work on N after upgrade.

btw: use Chinese if you can

**Comment by WanderMax** [comment]
Android M 的外置SD卡写权限问题, 点击之后还是无效...
其次, 这个应用成了xposed之后必备啊, 毕竟国产App总是乱建目录.
再次, 此项目会继续开发么? 用gradle+AS?

**Comment by Richard-Tung** [comment]
现在获取SD权限的方法是强行给应用的uid插个能写sd卡的gid进去 如果应用直接写SD应该是没问题的(我自己拿app试了下是可以写) 但好像有啥检测SD是否可读写的东西(大概是个系统函数之类的) 我之前翻了几遍adt给的源码都没找到...有头绪的话可以回复下
我开发环境还是Eclipse...AS还没用过...到时候可能会考虑试试...

**Comment by WanderMax** [comment]
https://github.com/pylerSM/XInternalSD
这个的应用SD卡写权限貌似对我的6.01生效了, 之前应用你的没有生效....

**Comment by Richard-Tung** [comment]
发现自己犯了个非常2的错误。。
试下新版1.4.3
https://github.com/Richard-Tung/SDLink/tree/binary

**Comment by WanderMax** [comment]
发现 我还是1.41.... 打开关于还没有版本号, 笑~~
版本好老了, 其次排除路径那里相对路径是什么意思?
比如用默认设置AppFile, 然后?

**Comment by WanderMax** [comment]
可以尝试用AS了, 毕竟谷歌亲儿子啊~~

**Comment by Richard-Tung** [comment]
排除是你想让应用直接访问哪些目录。。比如DCIM 如果你想在app里选照片的话。。
相对路径的话是允许app访问每个sd卡的这个目录
绝对路径的话是只允许访问指定sd卡的这个目录
上面那个独立路径设置也是一样
如果写相对路径则应用访问任意一张sd卡都会被加上这个路径（注意不会加默认的AppFile）
如果是绝对路径则访问任意一张sd卡都会被重定向到这个目录（或者你直接写sd卡根目录 则app就只能认到这一张sd卡）

**Comment by WanderMax** [comment]
也就是说 排除的是指定应用的访问目录
比如, 我把UC放进去了, 但是我却只想把 UCDownload 仍留在根目录, 这种事无法达到的对吧?

**Comment by Richard-Tung** [comment]
直接发邮件吧。。dyq@dyq.me 这issue好像给刷了一堆无关东西。。

**Comment by WanderMax** [comment]
v1.43 应用6.0+ 写入权限选项之后, 可以使用了
谢谢!
对于N, 等作者升级系统再说~~

**Comment by Richard-Tung** [comment]
N其实可以试一下。。SD那块好像没啥改动 有空我把m8拿出来刷个测下兼容性
